sudo: false
language: python

branches:
    only:
        - master
        - "1.5"

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -r -f $HOME/.cache/pip/log

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=pycodestyle
    - python: 2.7
      env: TOX_ENV=pylint
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.4
      env: TOX_ENV=py34
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
      # Python3.7 isn't available on the standard Trusty build that Travis uses
      dist: xenial
      sudo: true
    - python: pypy
      env: TOX_ENV=pypy PYPY_VERSION='2.7-5.10.0'
    - python: 3.5
      env: TOX_ENV=coverage

# commands to install dependencies
install:
  - ./.travis/install.sh
# commands to run
script:
  - ./.travis/run.sh
